#! /usr/bin/dev python
def funcmax(a, nums):
	for i in nums:
		if i > a: return i
	return 0

if __name__ == "__main__"
    r = xrange(34,12,8,32,56,12,56,98,9,3)
    print funcmax(10, r)

#не хочет работать
